Audio PR - Augmentation support [ Spectrogram ]
ROCm/rocAL pull request #124
Opened 2024-03-26 16:30 UTC by swetha097

- Add Spectrogram Filter support in rocAL

MIVisionX PR Link : [PR#1319](https://github.com/ROCm/MIVisionX/pull/1319)
NOTE: [PR#123](https://github.com/ROCm/rocAL/pull/123) to be merged before this PR

2024-05-02 20:16 UTC, rrawther commented
@swetha097 please add the MIVisionX version check and disable this feature until the next version of MIVisionX where audio feature will be enabled

2024-06-11 17:43 UTC, rrawther commented on tests/cpp_api/audio_tests/audio_tests.cpp
> +    std::cout << std::endl
please remove this emply line. The current way is correct

2024-06-11 17:45 UTC, rrawther commented on tests/cpp_api/audio_tests/audio_tests.cpp
> +    std::string file_list_path = "";  // User can modify this with the file list path if required
std::string constructor will create empty string by default. So = "" is not required. Please remove all such cases in other instances

2024-06-11 18:18 UTC, rrawther commented on tests/python_api/audio_unit_test.py
> +    if audio_path == "" and file_list == "":
empty() is better here
```suggestion
    if audio_path == "" and file_list == "":
```

2024-06-11 18:46 UTC, LakshmiKumar23 commented
@SundarRajan28 please resolve merge conflicts

2024-06-11 18:48 UTC, LakshmiKumar23 commented on rocAL/include/api/rocal_api_augmentation.h
> +extern "C" RocalTensor ROCAL_API_CALL rocalPreEmphasisFilter(RocalContext context,
Make sure to add ROCAL_AUDIO flag wherever required in this PR and others

2024-06-11 19:55 UTC, LakshmiKumar23 commented on rocAL/include/api/rocal_api_meta_data.h
> +extern "C" RocalMetaData ROCAL_API_CALL rocalCreateLabelReader(RocalContext rocal_context, const char* source_path, const char* file_list_path = "");
we should be consistent with initializing source_path and file_list_path

2024-06-11 19:57 UTC, LakshmiKumar23 commented on rocAL/include/augmentations/audio_augmentations/node_spectrogram.h
> +    double a = (2.0 * M_PI) / window_size;
check for divide by 0

2024-06-11 20:07 UTC, rrawther requested changes
Added review comments

2024-06-11 20:36 UTC, LakshmiKumar23 commented on tests/cpp_api/audio_tests/audio_tests.cpp
> +    std::cout << ">>>>>>> Running LABEL READER" << std::endl;
please remove the extra ">>>>" they are not needed

2024-06-11 20:36 UTC, LakshmiKumar23 commented on tests/cpp_api/audio_tests/audio_tests.cpp
> +            std::cout << ">>>>>>> Running SPECTROGRAM" << std::endl;
same as above, please refer to other tests

2024-06-13 17:35 UTC, LakshmiKumar23 commented on tests/python_api/README.md
>  **Available Test Cases**
Update line 138 to reflect `case 0-2`

2024-06-13 17:36 UTC, LakshmiKumar23 commented
@fiona-gladwin added a minor comment. Can be merged after that. Tests are passing

2024-06-13 18:25 UTC, fiona-gladwin commented on tests/python_api/audio_unit_test.py
> +    if audio_path == "" and file_list == "":
Changed to not

2024-06-13 18:26 UTC, fiona-gladwin commented on tests/python_api/README.md
>  **Available Test Cases**
Done

2024-06-13 20:03 UTC, LakshmiKumar23 approved these changes
Spectrogram tests pass

2024-06-13 20:05 UTC, rrawther approved these changes

2024-06-13 20:05 UTC, merged