Spectrogram example notebook
ROCm/rocAL pull request #181
Opened 2024-07-12 16:20 UTC by SundarRajan28

- Adding an example notebook for audio processing with spectrogram augmentation

2024-07-17 18:23 UTC, LakshmiKumar23 requested changes
@SundarRajan28 I am seeing a failure in the build stage for this notebook example:
```
Verify graph failed
[ERR]  {rocalVerify}  Invalid layout
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[13], [line 1](vscode-notebook-cell:?execution_count=13&line=1)
----> [1](vscode-notebook-cell:?execution_count=13&line=1) audio_pipeline.build()
      [2](vscode-notebook-cell:?execution_count=13&line=2) audioIteratorPipeline = ROCALAudioIterator(audio_pipeline)

File /usr/local/lib/python3.10/dist-packages/amd/rocal/pipeline.py:133, in Pipeline.build(self)
    [131](https://vscode-remote+ssh-002dremote-002bkapu.vscode-resource.vscode-cdn.net/usr/local/lib/python3.10/dist-packages/amd/rocal/pipeline.py:131) if (status != types.OK):
    [132](https://vscode-remote+ssh-002dremote-002bkapu.vscode-resource.vscode-cdn.net/usr/local/lib/python3.10/dist-packages/amd/rocal/pipeline.py:132)     print("Verify graph failed")
--> [133](https://vscode-remote+ssh-002dremote-002bkapu.vscode-resource.vscode-cdn.net/usr/local/lib/python3.10/dist-packages/amd/rocal/pipeline.py:133)     exit(0)
    [134](https://vscode-remote+ssh-002dremote-002bkapu.vscode-resource.vscode-cdn.net/usr/local/lib/python3.10/dist-packages/amd/rocal/pipeline.py:134) return self

NameError: name 'exit' is not defined
```

2024-07-17 18:30 UTC, LakshmiKumar23 commented
@SundarRajan28 also please add a readme to state pre reqs like librosa, matplotlib modules etc.

2024-07-18 21:45 UTC, rrawther commented on docs/examples/notebooks/spectrogram.ipynb
> +    "from __future__ import absolute_import\n",
do we need to use future? Can we replace those with newer python functions?

2024-07-18 22:00 UTC, rrawther commented on docs/examples/notebooks/spectrogram.ipynb
> +    "data_path = \"/data/MIVisionX-data/rocal_data/audio//wav/19-198-0000.wav\"\n",
I suggest getting the path from an environment variable instead of hardcoded path.
For e.g ROCAL_DATA_PATH = "path for rocal_data"

2024-07-18 22:01 UTC, rrawther requested changes
please address the review comments

2024-07-19 12:53 UTC, SundarRajan28 commented
@LakshmiKumar23 Can you share how you are building the example notebook so that I can replicate the issue? I have not encountered this error.

2024-07-22 21:19 UTC, LakshmiKumar23 commented
> @LakshmiKumar23 Can you share how you are building the example notebook so that I can replicate the issue? I have not encountered this error.

@SundarRajan28 I am running it on my vscode

2024-07-29 17:30 UTC, SundarRajan28 commented
@rrawther I have resolved the review comments

2024-07-29 18:55 UTC, rrawther approved these changes

2024-08-26 17:46 UTC, rrawther commented
@LakshmiKumar23: Can you please see if review comments are addressed and approve if it is ready to be merged

2024-08-28 06:18 UTC, LakshmiKumar23 commented on docs/examples/notebooks/spectrogram.ipynb
> +    "rocal_audio_data_path = os.path.join(os.environ['ROCAL_DATA_PATH'], \"rocal_data\", \"audio\")\n",
this line throws an error: `KeyError`. I have set the environment variable both on the vscode terminal and Moba. I will send it offline

2024-08-28 06:32 UTC, LakshmiKumar23 approved these changes
@rrawther @kiritigowda this notebook has been tested with package install for rpp and mivisionx . Can be merged

2024-08-28 15:47 UTC, merged