rocDecode integration in rocAL
ROCm/rocAL pull request #253
Opened 2024-12-18 12:09 UTC by fiona-gladwin

- Add support for rocDecode hardware decoder in rocAL
- Add support to create sequences using the seek operation in rocDecode, works seamlessly for H265 videos.

2024-12-23 20:31 UTC, kiritigowda commented
@fiona-gladwin failing to compile

```
/home/vsts/work/1/s/rocAL/source/decoders/video/rocdec_video_decoder.cpp:134:49: error: no member named 'selected_frame_dts_' in 'VideoSeekContext'
  134 |             required_frame_dts = video_seek_ctx.selected_frame_dts_;
      |                                  ~~~~~~~~~~~~~~ ^
/home/vsts/work/1/s/rocAL/source/decoders/video/rocdec_video_decoder.cpp:138:60: error: too many arguments to function call, expected at most 3, have 4
  138 |             _demuxer->Demux(&pvideo, &n_video_bytes, &pts, &dts);
      |             ~~~~~~~~~~~~~~~                                ^~~~
/home/vsts/work/1/rocm/share/rocdecode/utils/video_demuxer.h:156:14: note: 'Demux' declared here
  156 |         bool Demux(uint8_t **video, int *video_size, int64_t *pts = nullptr) {
      |              ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/vsts/work/1/s/rocAL/source/decoders/video/rocdec_video_decoder.cpp:23:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/iomanip:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ios_base.h:41:
```

2024-12-24 04:02 UTC, fiona-gladwin commented
> @fiona-gladwin failing to compile
> 
> ```
> /home/vsts/work/1/s/rocAL/source/decoders/video/rocdec_video_decoder.cpp:134:49: error: no member named 'selected_frame_dts_' in 'VideoSeekContext'
>   134 |             required_frame_dts = video_seek_ctx.selected_frame_dts_;
>       |                                  ~~~~~~~~~~~~~~ ^
> /home/vsts/work/1/s/rocAL/source/decoders/video/rocdec_video_decoder.cpp:138:60: error: too many arguments to function call, expected at most 3, have 4
>   138 |             _demuxer->Demux(&pvideo, &n_video_bytes, &pts, &dts);
>       |             ~~~~~~~~~~~~~~~                                ^~~~
> /home/vsts/work/1/rocm/share/rocdecode/utils/video_demuxer.h:156:14: note: 'Demux' declared here
>   156 |         bool Demux(uint8_t **video, int *video_size, int64_t *pts = nullptr) {
>       |              ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from /home/vsts/work/1/s/rocAL/source/decoders/video/rocdec_video_decoder.cpp:23:
> In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/iomanip:40:
> In file included from /usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ios_base.h:41:
> ```

@kiritigowda This PR required PR [#479](https://github.com/ROCm/rocDecode/pull/479) of rocDecode to be merged for successful compilation

2025-01-10 19:17 UTC, rrawther reviewed
Please address the review comments

2025-01-10 19:17 UTC, rrawther commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +        int required_n_frames = std::min(static_cast<int>(sequence_length), n_frame_returned);
Isn't the sequence_length always <= n_frame_returned. In line#144 please check if n_frame_returned < sequence_length and return error.
Remove this line

2025-01-10 19:17 UTC, rrawther commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +        for (int i = 0; i < required_n_frames; i++) {
change it to sequence_length. What if there in not enough frames in the sequence when there is EOF?

2025-01-10 19:17 UTC, rrawther commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +            if (dts >= requested_frame_dts) {
how is the dts value updated here. We are only returning pts in the call

2025-01-10 19:17 UTC, rrawther commented on rocAL/source/loaders/video/video_loader.cpp
> +    if (device_id < 0)
please set to 0 here as default instead

2025-01-13 16:43 UTC, LakshmiKumar23 commented
Corresponding [rocDecode PR](https://github.com/ROCm/rocDecode/pull/489) merged.

2025-01-14 00:41 UTC, LakshmiKumar23 commented on rocAL/include/decoders/image/decoder.h
> +    FFMPEG_SW_DECODE = 6,   //!< for video decoding using CPU and FFMPEG
Why is 5 not being used?. If we remove OVX_FFMPWG, please make FFMPEG_SW_DECODE=5

2025-01-14 00:42 UTC, LakshmiKumar23 commented on rocAL/include/decoders/video/rocdec_video_decoder.h
> +// this struct is used by videodecode and videodecodeMultiFiles to dump last frames to file
this comment does not make sense here. It's sample names for rocDecode library

2025-01-14 00:44 UTC, LakshmiKumar23 commented on rocAL/rocAL_hip/CMakeLists.txt
> +file (GLOB rocDecode_HIP_SOURCES ${ROCM_PATH}/share/rocdecode/utils/*.cpp )
what is rocDecode_HIP_SOURCES? There is no HIP vs HOST in this case

2025-01-15 17:27 UTC, LakshmiKumar23 commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +Copyright (c) 2024 Advanced Micro Devices, Inc. All rights reserved.
copyright `2025 -`

2025-01-15 17:28 UTC, LakshmiKumar23 commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +        WRN("GPU doesn't support codec!")
should be an ERR not WRN

2025-01-15 17:34 UTC, LakshmiKumar23 commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +            video_seek_ctx.seek_crit_ = SEEK_CRITERIA_FRAME_NUM;
Do we always seek with frame number? Is there a use case for seek with timestamp?

2025-01-15 17:36 UTC, LakshmiKumar23 commented on rocAL/source/loaders/video/video_loader_sharded.cpp
> +        _loaders[idx]->set_gpu_device_id(idx);
what can the max idx value be? In this function you only check `device_id < 0`. Needs to check upper limit too

2025-01-16 17:30 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +            video_seek_ctx.seek_crit_ = SEEK_CRITERIA_FRAME_NUM;
In rocAL we generally split the sequences based on the frame number and seek wrt frame number.
Seeking with timestamp is not used here

2025-01-17 19:06 UTC, rrawther commented on rocAL/include/decoders/image/decoder.h
> +    FFMPEG_HW_DECODE = 7,   //!< for video decoding using HW via FFMPEG
We need to remove FFMPEG_HW_DECODE option eventually

2025-01-17 19:08 UTC, rrawther commented on rocAL/include/decoders/video/rocdec_video_decoder.h
> +#if ENABLE_HIP
Please change it to single line #if ENABLE_HIP && ENABLE_ROCDECODE

2025-01-17 20:10 UTC, rrawther commented on rocAL/rocAL_hip/CMakeLists.txt
> +set (rocDecode_UTILS
rename to rocDecode_UTIL_SOURCES

2025-01-17 20:17 UTC, rrawther commented on rocAL/source/loaders/video/video_loader_sharded.cpp
> +        _loaders[idx]->set_gpu_device_id(idx);
I think that check needs to happen in higher level when we decide numshards

2025-01-17 23:55 UTC, rrawther requested changes
please address all the review comments. Some are not resolved

2025-01-18 03:09 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +        for (int i = 0; i < required_n_frames; i++) {
We take the min of sequence length or the n_frames returned as the n_frames_returned value can be lesser than sequence length

2025-01-18 03:27 UTC, fiona-gladwin commented on rocAL/rocAL_hip/CMakeLists.txt
> +set (rocDecode_UTILS
Done

2025-01-18 03:27 UTC, fiona-gladwin commented on rocAL/include/decoders/video/rocdec_video_decoder.h
> +#if ENABLE_HIP
Done

2025-01-18 03:27 UTC, fiona-gladwin commented on rocAL/source/api/rocal_api_data_loaders.cpp
> +#if ENABLE_ROCDECODE
Done, introduced new variable

2025-01-18 03:28 UTC, fiona-gladwin commented on rocAL/source/api/rocal_api_data_loaders.cpp
>          if (rocal_decode_device == RocalDecodeDevice::ROCAL_HW_DECODE)
Done

2025-01-18 03:28 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +#if ENABLE_HIP
Done

2025-01-20 16:56 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +            if (dts >= requested_frame_dts) {
The dts value returned by the demuxer is used to go to the correct position and start decoding from that point

2025-01-20 17:14 UTC, fiona-gladwin commented
> please address all the review comments. Some are not resolved

@rrawther Addressed all review comments Please check.

2025-01-24 17:51 UTC, rrawther approved these changes

2025-01-28 05:44 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +RocDecVideoDecoder::RocDecVideoDecoder(){};
Moved empty constructor definition to class

2025-01-30 00:02 UTC, rrawther approved these changes

2025-01-30 00:09 UTC, rrawther commented on cmake/FindrocDecode.cmake
> +    $ENV{rocDecode_PATH}/lib
I think this is still not done. Can you please fix this?

2025-01-30 00:12 UTC, rrawther requested changes
Please resolve all review comments

2025-01-30 00:17 UTC, rrawther approved these changes

2025-01-30 15:59 UTC, fiona-gladwin commented on rocAL/include/decoders/video/rocdec_video_decoder.h
> +        int seek_frame(AVRational avg_frame_rate, AVRational time_base, unsigned frame_number) override { return 0; }
Done

2025-01-30 15:59 UTC, fiona-gladwin commented on rocAL/rocAL_hip/CMakeLists.txt
> +file (GLOB rocDecode_HIP_SOURCES ${ROCM_PATH}/share/rocdecode/utils/*.cpp )
Done

2025-01-30 16:00 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +VideoDecoder::Status RocDecVideoDecoder::Decode(unsigned char *out_buffer, unsigned seek_frame_number, size_t sequence_length, size_t stride, int out_width, int out_height, int out_stride, AVPixelFor
Done

2025-01-30 16:00 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +Copyright (c) 2024 Advanced Micro Devices, Inc. All rights reserved.
Done

2025-01-30 16:00 UTC, fiona-gladwin commented on rocAL/source/decoders/video/rocdec_video_decoder.cpp
> +        WRN("GPU doesn't support codec!")
Done

2025-01-30 16:01 UTC, fiona-gladwin commented
> Please resolve all review comments

@LakshmiKumar23 and @rrawther  Resolved all review comments

2025-01-30 18:04 UTC, LakshmiKumar23 commented
> Nothing to review for docs.
> 
> However, these seem to be a lot of changes. Do any of them need to be tracked in the changelog or the documentation?

@spolifroni-amd yes you are right
@fiona-gladwin  please add a CHANGELOG. This is a big addition. Also needs to be added in docs

2025-01-30 18:24 UTC, rrawther requested changes
Please add changelog and doc for this

2025-01-30 18:25 UTC, LakshmiKumar23 commented on docs/user_guide/ch1.md
> +| Video             | Decodes videos using FFmpeg/rocDecode  |
Please add a link to [rocDecode](https://www.github.com/ROCm/rocDecode)

2025-01-30 18:26 UTC, fiona-gladwin commented on docs/user_guide/ch1.md
> +| Video             | Decodes videos using FFmpeg/rocDecode  |
Done

2025-01-30 18:26 UTC, fiona-gladwin commented
> Please add changelog and doc for this

Done

2025-01-30 18:27 UTC, LakshmiKumar23 submitted a review, later dismissed

2025-01-30 18:29 UTC, fiona-gladwin commented on cmake/FindrocDecode.cmake
> +    $ENV{rocDecode_PATH}/include/rocdecode
Updated with the CMake from rocDecode library

2025-01-31 00:54 UTC, rrawther submitted a review, later dismissed

2025-02-03 16:30 UTC, rrawther commented
@kiritigowda : Not sure why the CI is failing in this. I would like to merge this PR

2025-02-04 14:31 UTC, fiona-gladwin commented
> @fiona-gladwin - the main readme requires updates to the prerequisites and update the version of the rocAL (2.2.0 to 2.3.0)

Done, Please check

2025-02-04 18:28 UTC, rrawther commented
@kiritigowda please check and merge this PR

2025-02-05 02:30 UTC, merged