Add webdataset reader python example and index file creation script
ROCm/rocAL pull request #255
Opened 2024-12-27 14:43 UTC by SundarRajan28

- Adds webdataset reader python example
- Adds tar2idx script to create idx files from tar files for webdataset reader
Note: PR #230 needs to be merged first after which the file changes will reduce to 5

2025-01-06 16:44 UTC, spolifroni-amd reviewed
No docs need to be reviewed.

2025-01-06 19:28 UTC, kiritigowda commented
@SundarRajan28 - please resolve conflicts

2025-01-15 17:14 UTC, LakshmiKumar23 commented on tests/python_api/web_dataset_reader.py
> +# Copyright (c) 2018 - 2023 Advanced Micro Devices, Inc. All rights reserved.
copyright `2025 - `

2025-01-15 17:20 UTC, LakshmiKumar23 commented on tools/tar2idx.py
> +# Copyright (c) 2024 Advanced Micro Devices, Inc. All rights reserved.
same as above

2025-01-15 17:21 UTC, LakshmiKumar23 commented on tools/tar2idx.py
> +    def split_filepath_name(path):
add an empty line between functions

2025-01-15 17:26 UTC, LakshmiKumar23 commented
@swetha097 please clean up the README under tools with code blocks and update instructions to python3 wherever required

2025-01-16 21:21 UTC, rrawther commented on tests/python_api/web_dataset_reader.py
> +            path=image_path, ext=[{'JPEG', 'cls'}], index_paths=index_file, missing_components_behavior=types.MISSING_COMPONENT_ERROR,
please move this to line above to combine with the fn

2025-01-16 21:33 UTC, rrawther commented on tests/python_api/web_dataset_reader.py
> +        if not isExist:
remove isExist and change this to "if not os.path.exists(path)"

2025-01-16 21:34 UTC, rrawther commented on tests/python_api/web_dataset_reader.py
> +        pipe, display=0, device=device, device_id=args.local_rank)
move this to previous line

2025-01-16 21:35 UTC, rrawther commented on tests/python_api/web_dataset_reader.py
> +            if i == 0:
combine this with the next if "if i==0 and args.print_tensor:

2025-01-16 21:36 UTC, rrawther commented on tests/python_api/web_dataset_reader.py
> +                    sys.stdout.write("\r Mini-batch " + str(i))
why there is mix of std::cout and print statements

2025-01-16 21:38 UTC, rrawther commented on tests/python_api/web_dataset_reader.py
> +                draw_patches(image_batch[element],
Is cnt same as element? If so, please use it instead of cnt and remove cnt

2025-01-16 21:41 UTC, rrawther commented on tools/tar2idx.py
> +# Permission is hereby granted, free of charge, to any person obtaining a copy
I suggest remove the github reference for "imgtorec.py" and add the script file here

2025-01-16 21:41 UTC, rrawther requested changes
Please address the review comments

2025-01-17 13:54 UTC, SundarRajan28 commented on tests/python_api/web_dataset_reader.py
> +                draw_patches(image_batch[element],
cnt is used to track the samples count across all batches. element is local to the for loop so cannot be used for cnt

2025-01-17 19:03 UTC, rrawther approved these changes

2025-01-17 19:04 UTC, merged